/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CommunityHub } from "./CommunityHub";
export type { ElectionResults } from "./ElectionResults";
export type { ICommunityHub } from "./ICommunityHub";
export type { IElectionResults } from "./IElectionResults";
