/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelinContracts from "./openzeppelin-contracts";
export type { openzeppelinContracts };
import type * as src from "./src";
export type { src };
export * as factories from "./factories";
export type { Ownable } from "./openzeppelin-contracts/contracts/access/Ownable";
export { Ownable__factory } from "./factories/openzeppelin-contracts/contracts/access/Ownable__factory";
export type { CommunityHub } from "./src/CommunityHub";
export { CommunityHub__factory } from "./factories/src/CommunityHub__factory";
export type { ElectionResults } from "./src/ElectionResults";
export { ElectionResults__factory } from "./factories/src/ElectionResults__factory";
export type { ICommunityHub } from "./src/ICommunityHub";
export { ICommunityHub__factory } from "./factories/src/ICommunityHub__factory";
export type { IElectionResults } from "./src/IElectionResults";
export { IElectionResults__factory } from "./factories/src/IElectionResults__factory";
