// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"context"

	"github.com/Khan/genqlient/graphql"
	"github.com/ethereum/go-ethereum/common"
)

// GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutput includes the requested fields of the GraphQL type FarcasterChannelsOutput.
type GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutput struct {
	FarcasterChannel []GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannel `json:"FarcasterChannel"`
	PageInfo         GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo           `json:"pageInfo"`
}

// GetFarcasterChannel returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutput.FarcasterChannel, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutput) GetFarcasterChannel() []GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannel {
	return v.FarcasterChannel
}

// GetPageInfo returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutput.PageInfo, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutput) GetPageInfo() GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo {
	return v.PageInfo
}

// GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannel includes the requested fields of the GraphQL type FarcasterChannel.
type GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannel struct {
	Participants []GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipant `json:"participants"`
}

// GetParticipants returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannel.Participants, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannel) GetParticipants() []GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipant {
	return v.Participants
}

// GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipant includes the requested fields of the GraphQL type FarcasterChannelParticipant.
type GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipant struct {
	Participant GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial `json:"participant"`
}

// GetParticipant returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipant.Participant, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipant) GetParticipant() GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial {
	return v.Participant
}

// GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial includes the requested fields of the GraphQL type Social.
type GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial struct {
	UserAddress common.Address `json:"userAddress"`
	ProfileName string         `json:"profileName"`
	Fid         string         `json:"fid"`
	// blockchain addresses associated with the social profile
	UserAssociatedAddresses []common.Address `json:"userAssociatedAddresses"`
	FollowerCount           int              `json:"followerCount"`
	FollowingCount          int              `json:"followingCount"`
}

// GetUserAddress returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial.UserAddress, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial) GetUserAddress() common.Address {
	return v.UserAddress
}

// GetProfileName returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial.ProfileName, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial) GetProfileName() string {
	return v.ProfileName
}

// GetFid returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial.Fid, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial) GetFid() string {
	return v.Fid
}

// GetUserAssociatedAddresses returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial.UserAssociatedAddresses, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial) GetUserAssociatedAddresses() []common.Address {
	return v.UserAssociatedAddresses
}

// GetFollowerCount returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial.FollowerCount, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial) GetFollowerCount() int {
	return v.FollowerCount
}

// GetFollowingCount returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial.FollowingCount, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputFarcasterChannelParticipantsFarcasterChannelParticipantParticipantSocial) GetFollowingCount() int {
	return v.FollowingCount
}

// GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo includes the requested fields of the GraphQL type PageInfo.
type GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo struct {
	HasNextPage bool   `json:"hasNextPage"`
	HasPrevPage bool   `json:"hasPrevPage"`
	NextCursor  string `json:"nextCursor"`
	PrevCursor  string `json:"prevCursor"`
}

// GetHasNextPage returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetHasPrevPage returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo.HasPrevPage, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo) GetHasPrevPage() bool {
	return v.HasPrevPage
}

// GetNextCursor returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo.NextCursor, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo) GetNextCursor() string {
	return v.NextCursor
}

// GetPrevCursor returns GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo.PrevCursor, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutputPageInfo) GetPrevCursor() string {
	return v.PrevCursor
}

// GetFarcasterUsersByChannelResponse is returned by GetFarcasterUsersByChannel on success.
type GetFarcasterUsersByChannelResponse struct {
	FarcasterChannels GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutput `json:"FarcasterChannels"`
}

// GetFarcasterChannels returns GetFarcasterUsersByChannelResponse.FarcasterChannels, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersByChannelResponse) GetFarcasterChannels() GetFarcasterUsersByChannelFarcasterChannelsFarcasterChannelsOutput {
	return v.FarcasterChannels
}

// GetFarcasterUsersWithAssociatedAddressesResponse is returned by GetFarcasterUsersWithAssociatedAddresses on success.
type GetFarcasterUsersWithAssociatedAddressesResponse struct {
	Socials GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutput `json:"Socials"`
}

// GetSocials returns GetFarcasterUsersWithAssociatedAddressesResponse.Socials, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersWithAssociatedAddressesResponse) GetSocials() GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutput {
	return v.Socials
}

// GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutput includes the requested fields of the GraphQL type SocialsOutput.
type GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutput struct {
	Social   []GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputSocial `json:"Social"`
	PageInfo GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo `json:"pageInfo"`
}

// GetSocial returns GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutput.Social, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutput) GetSocial() []GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputSocial {
	return v.Social
}

// GetPageInfo returns GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutput.PageInfo, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutput) GetPageInfo() GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo {
	return v.PageInfo
}

// GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo includes the requested fields of the GraphQL type PageInfo.
type GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo struct {
	NextCursor  string `json:"nextCursor"`
	PrevCursor  string `json:"prevCursor"`
	HasNextPage bool   `json:"hasNextPage"`
	HasPrevPage bool   `json:"hasPrevPage"`
}

// GetNextCursor returns GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo.NextCursor, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo) GetNextCursor() string {
	return v.NextCursor
}

// GetPrevCursor returns GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo.PrevCursor, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo) GetPrevCursor() string {
	return v.PrevCursor
}

// GetHasNextPage returns GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetHasPrevPage returns GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo.HasPrevPage, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputPageInfo) GetHasPrevPage() bool {
	return v.HasPrevPage
}

// GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputSocial includes the requested fields of the GraphQL type Social.
type GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputSocial struct {
	UserId string `json:"userId"`
	// blockchain addresses associated with the social profile
	UserAssociatedAddresses []common.Address `json:"userAssociatedAddresses"`
}

// GetUserId returns GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputSocial.UserId, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputSocial) GetUserId() string {
	return v.UserId
}

// GetUserAssociatedAddresses returns GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputSocial.UserAssociatedAddresses, and is useful for accessing the field via an interface.
func (v *GetFarcasterUsersWithAssociatedAddressesSocialsSocialsOutputSocial) GetUserAssociatedAddresses() []common.Address {
	return v.UserAssociatedAddresses
}

// GetTokenBalancesResponse is returned by GetTokenBalances on success.
type GetTokenBalancesResponse struct {
	TokenBalances GetTokenBalancesTokenBalancesTokenBalancesOutput `json:"TokenBalances"`
}

// GetTokenBalances returns GetTokenBalancesResponse.TokenBalances, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesResponse) GetTokenBalances() GetTokenBalancesTokenBalancesTokenBalancesOutput {
	return v.TokenBalances
}

// GetTokenBalancesTokenBalancesTokenBalancesOutput includes the requested fields of the GraphQL type TokenBalancesOutput.
type GetTokenBalancesTokenBalancesTokenBalancesOutput struct {
	TokenBalance []GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalance `json:"TokenBalance"`
	PageInfo     GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo       `json:"pageInfo"`
}

// GetTokenBalance returns GetTokenBalancesTokenBalancesTokenBalancesOutput.TokenBalance, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesTokenBalancesTokenBalancesOutput) GetTokenBalance() []GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalance {
	return v.TokenBalance
}

// GetPageInfo returns GetTokenBalancesTokenBalancesTokenBalancesOutput.PageInfo, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesTokenBalancesTokenBalancesOutput) GetPageInfo() GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo {
	return v.PageInfo
}

// GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo includes the requested fields of the GraphQL type PageInfo.
type GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo struct {
	NextCursor  string `json:"nextCursor"`
	PrevCursor  string `json:"prevCursor"`
	HasNextPage bool   `json:"hasNextPage"`
	HasPrevPage bool   `json:"hasPrevPage"`
}

// GetNextCursor returns GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo.NextCursor, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo) GetNextCursor() string {
	return v.NextCursor
}

// GetPrevCursor returns GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo.PrevCursor, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo) GetPrevCursor() string {
	return v.PrevCursor
}

// GetHasNextPage returns GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetHasPrevPage returns GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo.HasPrevPage, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesTokenBalancesTokenBalancesOutputPageInfo) GetHasPrevPage() bool {
	return v.HasPrevPage
}

// GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalance includes the requested fields of the GraphQL type TokenBalance.
type GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalance struct {
	// Nested Query allowing to retrieve address, domain names, social profiles of the owner
	Owner GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalanceOwnerWallet `json:"owner"`
	// Token amount the address currently holds
	Amount string `json:"amount"`
}

// GetOwner returns GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalance.Owner, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalance) GetOwner() GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalanceOwnerWallet {
	return v.Owner
}

// GetAmount returns GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalance.Amount, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalance) GetAmount() string {
	return v.Amount
}

// GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalanceOwnerWallet includes the requested fields of the GraphQL type Wallet.
type GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalanceOwnerWallet struct {
	// Returns addresses associated with the identity input
	Addresses []common.Address `json:"addresses"`
}

// GetAddresses returns GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalanceOwnerWallet.Addresses, and is useful for accessing the field via an interface.
func (v *GetTokenBalancesTokenBalancesTokenBalancesOutputTokenBalanceOwnerWallet) GetAddresses() []common.Address {
	return v.Addresses
}

// GetTokenDetailsResponse is returned by GetTokenDetails on success.
type GetTokenDetailsResponse struct {
	Token GetTokenDetailsToken `json:"Token"`
}

// GetToken returns GetTokenDetailsResponse.Token, and is useful for accessing the field via an interface.
func (v *GetTokenDetailsResponse) GetToken() GetTokenDetailsToken { return v.Token }

// GetTokenDetailsToken includes the requested fields of the GraphQL type Token.
type GetTokenDetailsToken struct {
	// Name of the token, mirrored from the smart contract
	Name string `json:"name"`
	// Symbol of the token, mirrored from the smart contract
	Symbol string `json:"symbol"`
	// The number of decimal places this token uses, default to 18
	Decimals int `json:"decimals"`
	// Amount of tokens in the protocol
	TotalSupply string `json:"totalSupply"`
}

// GetName returns GetTokenDetailsToken.Name, and is useful for accessing the field via an interface.
func (v *GetTokenDetailsToken) GetName() string { return v.Name }

// GetSymbol returns GetTokenDetailsToken.Symbol, and is useful for accessing the field via an interface.
func (v *GetTokenDetailsToken) GetSymbol() string { return v.Symbol }

// GetDecimals returns GetTokenDetailsToken.Decimals, and is useful for accessing the field via an interface.
func (v *GetTokenDetailsToken) GetDecimals() int { return v.Decimals }

// GetTotalSupply returns GetTokenDetailsToken.TotalSupply, and is useful for accessing the field via an interface.
func (v *GetTokenDetailsToken) GetTotalSupply() string { return v.TotalSupply }

type TokenBlockchain string

const (
	TokenBlockchainEthereum TokenBlockchain = "ethereum"
	TokenBlockchainPolygon  TokenBlockchain = "polygon"
	TokenBlockchainBase     TokenBlockchain = "base"
	TokenBlockchainZora     TokenBlockchain = "zora"
)

// __GetFarcasterUsersByChannelInput is used internally by genqlient
type __GetFarcasterUsersByChannelInput struct {
	ChannelId string `json:"channelId"`
	Limit     int    `json:"limit"`
	Cursor    string `json:"cursor"`
}

// GetChannelId returns __GetFarcasterUsersByChannelInput.ChannelId, and is useful for accessing the field via an interface.
func (v *__GetFarcasterUsersByChannelInput) GetChannelId() string { return v.ChannelId }

// GetLimit returns __GetFarcasterUsersByChannelInput.Limit, and is useful for accessing the field via an interface.
func (v *__GetFarcasterUsersByChannelInput) GetLimit() int { return v.Limit }

// GetCursor returns __GetFarcasterUsersByChannelInput.Cursor, and is useful for accessing the field via an interface.
func (v *__GetFarcasterUsersByChannelInput) GetCursor() string { return v.Cursor }

// __GetFarcasterUsersWithAssociatedAddressesInput is used internally by genqlient
type __GetFarcasterUsersWithAssociatedAddressesInput struct {
	Limit  int    `json:"limit"`
	Cursor string `json:"cursor"`
}

// GetLimit returns __GetFarcasterUsersWithAssociatedAddressesInput.Limit, and is useful for accessing the field via an interface.
func (v *__GetFarcasterUsersWithAssociatedAddressesInput) GetLimit() int { return v.Limit }

// GetCursor returns __GetFarcasterUsersWithAssociatedAddressesInput.Cursor, and is useful for accessing the field via an interface.
func (v *__GetFarcasterUsersWithAssociatedAddressesInput) GetCursor() string { return v.Cursor }

// __GetTokenBalancesInput is used internally by genqlient
type __GetTokenBalancesInput struct {
	TokenAddress common.Address  `json:"tokenAddress"`
	Blockchain   TokenBlockchain `json:"blockchain"`
	Limit        int             `json:"limit"`
	Cursor       string          `json:"cursor"`
}

// GetTokenAddress returns __GetTokenBalancesInput.TokenAddress, and is useful for accessing the field via an interface.
func (v *__GetTokenBalancesInput) GetTokenAddress() common.Address { return v.TokenAddress }

// GetBlockchain returns __GetTokenBalancesInput.Blockchain, and is useful for accessing the field via an interface.
func (v *__GetTokenBalancesInput) GetBlockchain() TokenBlockchain { return v.Blockchain }

// GetLimit returns __GetTokenBalancesInput.Limit, and is useful for accessing the field via an interface.
func (v *__GetTokenBalancesInput) GetLimit() int { return v.Limit }

// GetCursor returns __GetTokenBalancesInput.Cursor, and is useful for accessing the field via an interface.
func (v *__GetTokenBalancesInput) GetCursor() string { return v.Cursor }

// __GetTokenDetailsInput is used internally by genqlient
type __GetTokenDetailsInput struct {
	TokenAddress common.Address  `json:"tokenAddress"`
	Blockchain   TokenBlockchain `json:"blockchain"`
}

// GetTokenAddress returns __GetTokenDetailsInput.TokenAddress, and is useful for accessing the field via an interface.
func (v *__GetTokenDetailsInput) GetTokenAddress() common.Address { return v.TokenAddress }

// GetBlockchain returns __GetTokenDetailsInput.Blockchain, and is useful for accessing the field via an interface.
func (v *__GetTokenDetailsInput) GetBlockchain() TokenBlockchain { return v.Blockchain }

// The query or mutation executed by GetFarcasterUsersByChannel.
const GetFarcasterUsersByChannel_Operation = `
query GetFarcasterUsersByChannel ($channelId: String, $limit: Int, $cursor: String) {
	FarcasterChannels(input: {filter:{channelId:{_eq:$channelId}},blockchain:ALL,limit:$limit,cursor:$cursor}) {
		FarcasterChannel {
			participants {
				participant {
					userAddress
					profileName
					fid: userId
					userAssociatedAddresses
					followerCount
					followingCount
				}
			}
		}
		pageInfo {
			hasNextPage
			hasPrevPage
			nextCursor
			prevCursor
		}
	}
}
`

func GetFarcasterUsersByChannel(
	ctx context.Context,
	client graphql.Client,
	channelId string,
	limit int,
	cursor string,
) (*GetFarcasterUsersByChannelResponse, error) {
	req := &graphql.Request{
		OpName: "GetFarcasterUsersByChannel",
		Query:  GetFarcasterUsersByChannel_Operation,
		Variables: &__GetFarcasterUsersByChannelInput{
			ChannelId: channelId,
			Limit:     limit,
			Cursor:    cursor,
		},
	}
	var err error

	var data GetFarcasterUsersByChannelResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetFarcasterUsersWithAssociatedAddresses.
const GetFarcasterUsersWithAssociatedAddresses_Operation = `
query GetFarcasterUsersWithAssociatedAddresses ($limit: Int, $cursor: String) {
	Socials(input: {filter:{dappName:{_eq:farcaster}},blockchain:ethereum,limit:$limit,cursor:$cursor}) {
		Social {
			userId
			userAssociatedAddresses
		}
		pageInfo {
			nextCursor
			prevCursor
			hasNextPage
			hasPrevPage
		}
	}
}
`

func GetFarcasterUsersWithAssociatedAddresses(
	ctx context.Context,
	client graphql.Client,
	limit int,
	cursor string,
) (*GetFarcasterUsersWithAssociatedAddressesResponse, error) {
	req := &graphql.Request{
		OpName: "GetFarcasterUsersWithAssociatedAddresses",
		Query:  GetFarcasterUsersWithAssociatedAddresses_Operation,
		Variables: &__GetFarcasterUsersWithAssociatedAddressesInput{
			Limit:  limit,
			Cursor: cursor,
		},
	}
	var err error

	var data GetFarcasterUsersWithAssociatedAddressesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetTokenBalances.
const GetTokenBalances_Operation = `
query GetTokenBalances ($tokenAddress: Address!, $blockchain: TokenBlockchain!, $limit: Int, $cursor: String) {
	TokenBalances(input: {filter:{tokenAddress:{_eq:$tokenAddress}},blockchain:$blockchain,limit:$limit,cursor:$cursor}) {
		TokenBalance {
			owner {
				addresses
			}
			amount
		}
		pageInfo {
			nextCursor
			prevCursor
			hasNextPage
			hasPrevPage
		}
	}
}
`

func GetTokenBalances(
	ctx context.Context,
	client graphql.Client,
	tokenAddress common.Address,
	blockchain TokenBlockchain,
	limit int,
	cursor string,
) (*GetTokenBalancesResponse, error) {
	req := &graphql.Request{
		OpName: "GetTokenBalances",
		Query:  GetTokenBalances_Operation,
		Variables: &__GetTokenBalancesInput{
			TokenAddress: tokenAddress,
			Blockchain:   blockchain,
			Limit:        limit,
			Cursor:       cursor,
		},
	}
	var err error

	var data GetTokenBalancesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

// The query or mutation executed by GetTokenDetails.
const GetTokenDetails_Operation = `
query GetTokenDetails ($tokenAddress: Address!, $blockchain: TokenBlockchain!) {
	Token(input: {address:$tokenAddress,blockchain:$blockchain}) {
		name
		symbol
		decimals
		totalSupply
	}
}
`

func GetTokenDetails(
	ctx context.Context,
	client graphql.Client,
	tokenAddress common.Address,
	blockchain TokenBlockchain,
) (*GetTokenDetailsResponse, error) {
	req := &graphql.Request{
		OpName: "GetTokenDetails",
		Query:  GetTokenDetails_Operation,
		Variables: &__GetTokenDetailsInput{
			TokenAddress: tokenAddress,
			Blockchain:   blockchain,
		},
	}
	var err error

	var data GetTokenDetailsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
